export default {
  object: "object",
  dataSource: "dataSource",
  string: "string",
  number: "number",
  img: "img",
  longtext: "longtext",
  boolean: "boolean",
  array: "array",
  ignore: "ignore",
  editor: "editor",
  audio: "audio" /** 音视频上传 */,
  select: "select" /** select下拉选择器 */,
  timestamp: "timestamp" /** 时间戳(日期时间选择器) */,
  css4number: "css4number" /** 4方向css数值编辑器 */,
  jsonUpload: "jsonUpdload" /** 上传json文件 */,
  animation: "animation" /** 上传动画文件 */,
};
